// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iMrRDRgwos1Cho73L9G8A4
// Component: -9_P_H8B0WPG
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: iMrRDRgwos1Cho73L9G8A4/projectcss
import sty from "./PlasmicDaterangenextJs.module.css"; // plasmic-import: -9_P_H8B0WPG/css

createPlasmicElementProxy;

export const PlasmicDaterangenextJs__VariantProps = new Array();

export const PlasmicDaterangenextJs__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDaterangenextJs__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDaterangenextJs__ArgProps,
          internalVariantPropNames: PlasmicDaterangenextJs__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDaterangenextJs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDaterangenextJs";
  } else {
    func.displayName = `PlasmicDaterangenextJs.${nodeName}`;
  }
  return func;
}

export const PlasmicDaterangenextJs = Object.assign(
  // Top-level PlasmicDaterangenextJs renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicDaterangenextJs
    internalVariantProps: PlasmicDaterangenextJs__VariantProps,
    internalArgProps: PlasmicDaterangenextJs__ArgProps
  }
);

export default PlasmicDaterangenextJs;
/* prettier-ignore-end */
